name: firebase_instance_id
description: A Flutter plugin to retrieve the Firebase App Instance ID.
version: 1.1.0
homepage: https://dev.cingulo.com
repository: https://github.com/cingulo/firebase_instance_id
documentation: https://github.com/cingulo/firebase_instance_id/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cingulo.firebase_instance_id
        pluginClass: FirebaseInstanceIdPlugin
      ios:
        pluginClass: FirebaseInstanceIdPlugin
